paullouisageneau/libjuice

CMakeLists.txt, src/addr.c, src/addr.h, src/agent.c, src/random.c, src/socket.h, src/stun.c, src/udp.c
- Fixed compilation for Windows
- Enhanced addresses listing for non-Linux platforms
=> Compilation support for Windows

CMakeLists.txt, cmake/Modules/FindNettle.cmake, src/agent.c, src/ice.c, src/random.c
This PR adds support for compilation on MacOS.
=> MacOS support

CMakeLists.txt, README.md, test/connectivity.c, test/crc32.c, test/stun.c
This PR splits the different tests into multiple files.
=> Split tests into multiple files

CMakeLists.txt, src/agent.c, test/connectivity.c, test/main.c, test/server.c
=> Fix regression with server reflexive candidates

src/agent.c
Fixes https://github.com/paullouisageneau/libdatachannel/issues/43
=> Only destroy agent from thread when requested

src/addr.c
Should fix https://github.com/paullouisageneau/libjuice/issues/14
=> Fix address zeroing on mapping/unmapping

src/agent.c, src/thread.h
Should fix https://github.com/paullouisageneau/libdatachannel/issues/106
=> Specify calling convention for thread entry on Windows

src/agent.c, src/agent.h, src/ice.c, src/ice.h
- Better error reporting for SDP parsing
- Increased maximum number of candidate pairs
=> Enhance candidates handling

src/stun.c
Fixes https://github.com/paullouisageneau/libjuice/issues/29
=> Fix format in stun_read()

CMakeLists.txt
Fixes https://github.com/paullouisageneau/libjuice/issues/34
=> Fix CMake include path

include/juice/juice.h, src/log.c
This PR introduces atomics to enhance logger performance and adds the log level none.
=> Use atomics for logging

CMakeLists.txt
This PR adds `NO_TESTS` parameter to CMake.
=> Add NO_TESTS parameter

src/agent.c
This PR implements aggressive pair nomination, _i.e._ in controlling mode, it will nominate pairs as soon as possible at the cost of maybe changing later during the process.
=> Aggressive pair nomination

src/stun.c, test/stun.c
Fixes https://github.com/paullouisageneau/libjuice/issues/58
=> Fix htonll and ice-controlling/ice-controlled attributes

include/juice/juice.h, src/agent.c, src/agent.h, src/juice.c, src/udp.c, src/udp.h
This PR implements IP Differenciated Services (aka DiffServ) by introducing a special send function to the API `juice_send_diffserv()` allowing to specify the DS value.
=> IP Differenciated Services support

src/agent.c, src/agent.h
This PR explicitly synchronizes internal and external datagram sending.
=> Synchronize sending

src/agent.c, src/ice.c
This PR fixes the foundation on trickled local reflexive candidates.
=> Fix local reflexive candidates foundation

CMakeLists.txt, Makefile, README.md, include/juice/juice.h, src/addr.c, src/addr.h, src/agent.c, src/agent.h, src/juice.c, src/server.c, src/server.h, src/stun.c, src/stun.h, src/turn.c, src/turn.h, src/udp.c, test/gathering.c, test/main.c, test/server.c, test/turn.c
This PR implements a STUN/TURN server alongside the agent.
=> Add server implementation

include/juice/juice.h, src/addr.c, src/addr.h, src/juice.c, src/server.c, src/server.h, src/stun.c, src/udp.c, src/udp.h, test/server.c
- Rework server API
- Allow to specify binding and external addresses
=> Enhancements for server

src/agent.c, src/ice.c, src/ice.h
This PR fixes the priority attribute value computation in STUN binding requests.
=> Fix priority in STUN binding requests

CMakeLists.txt, src/agent.c, src/agent.h, test/conflict.c, test/main.c
This PR fixes ICE role conflict resolution and introduces a test for ICE role conflict.
=> Fix ICE role conflict resolution

src/agent.c
This PR fixes entry address matching to only select a relayed entry when the incoming datagram was relayed.
Fixes https://github.com/paullouisageneau/libjuice/issues/78
=> Fix entry matching

src/agent.c
This PR makes the agent fail the candidate pair check on non-symmetric response source address as mandated in [RFC 8445](https://tools.ietf.org/html/rfc8445#section-7.2.5.2.1).
=> Fail check on non-symmetric address

src/agent.c, src/server.c, src/udp.c, src/udp.h
Fixes https://github.com/paullouisageneau/libjuice/issues/91
=> Fix IPv4 only support on Windows and MacOS

src/juice.c
Fixes https://github.com/paullouisageneau/libjuice/issues/95
=> Fix warnings with NO_SERVER

CMakeLists.txt
Added a bundle identifier for the tests executable
=> Fixed to build for iOS

src/log.c
`localtime()` is not guaranteed to be thread-safe. This PR uses `localtime_r()` instead (or `localtime_s` on Windows).
=> Do not use localtime to ensure thread safety

src/stun.c
This PR fixes computation of the MESSAGE-INTEGRITY-SHA256 attribute (an incorrect message length field was taken into account when calculating the HMAC) and changes the order with MESSAGE-INTEGRITY attribute. This prevents possible authentication issues with TURN servers enforcing the last version of the STUN protocol.
=> Fix MESSAGE-INTEGRITY-SHA256 attribute

src/agent.c
@paullouisageneau 
I am try to fix stale nonce error, it seems work
=> Fix stale nonce error

src/agent.c, src/stun.c, src/turn.c, src/turn.h
This PR refactors TURN Refresh and Stale Nonce handling on top of https://github.com/paullouisageneau/libjuice/pull/108
It adds an immediate retry after 438 Stale Nonce error and also fixes a few minor issues with TURN Refresh. 
Fixes https://github.com/paullouisageneau/libjuice/issues/106
=> Enhance TURN Refresh fix and Stale Nonce handling

src/agent.c
This PR makes nomination conform to [RFC 8845](https://datatracker.ietf.org/doc/html/rfc8445).
=> Regular nomination

src/ice.c
Fixes https://github.com/paullouisageneau/libjuice/issues/140
=> Add 'ice2' option in generated SDP

src/agent.c
Since STUN keepalives from a remote relayed peer will be received through the corresponding TURN channel, it makes sense to also send STUN keepalives through it rather than using TURN Send Indications.
=> Send STUN keepalives through TURN channel

CMakeLists.txt, src/conn.c, src/conn.h, src/conn_thread.c, test/main.c, test/mux.c, test/thread.c
This PR enhances connections registry lifecycle and add tests for the alternative concurrency modes.
=> Refactor connections registry

src/agent.c
This PR fixes an issue caused by candidates being reset when `juice_set_remote_description()` is called multiple times. This result in connectivity issues as existing candidates pairs might reference reset candidates, in particular peer reflexive ones.
=> Fix inconsistent connectivity when setting remote description mutliple times

src/conn_mux.c
Fixes https://github.com/paullouisageneau/libjuice/issues/163
=> Fix mux map count not incremented if replacing a deleted entry

src/conn_poll.c, src/conn_thread.c
I ran cppcheck over the library and it returned two memory leaks. I fixed them.
=> Leak-Fixes

src/agent.c
This PR fixes a race condition resulting in local peer reflexive candidates being created before local host candidates if a STUN binding message from the remote peer arrives early.
=> Fix race condition potentially resulting in early prflx candidates

CMakeLists.txt, README.md, src/agent.c, src/agent.h, src/ice.h
This PR implements Consent Freshness from RFC 7675.
=> Add support for Consent Freshness

src/udp.c
JLOG_ERROR() call lack parameter "sockerrno"
=> Fix JLOG call lacking parameter

src/agent.c, test/bind.c, test/conflict.c, test/connectivity.c, test/gathering.c, test/mux.c, test/notrickle.c, test/server.c, test/thread.c, test/turn.c
This PR changes triggered checks logic to comply to [RFC 8445](https://www.rfc-editor.org/rfc/rfc8445.html#section-7.3.1.4).
=> Fix triggered checks logic to match specification

src/agent.c, src/agent.h, test/mux.c
This PR removes the existing retransmission limitation logic and adds a proper nomination timeout instead.
=> Add nomination timeout

src/agent.c, src/conn_mux.c, src/conn_poll.c, src/conn_thread.c, src/server.c, src/thread.h
This PR adds support for thread names to help debugging.
=> Add support for thread names

src/log.c
log_mutex is not unlock for return
=> Fix deadlock for log

src/agent.c
When receiving an unrecoverable STUN error, the pair should be marked as failed.
=> Fix handling of unrecoverable STUN error during check

src/agent.h
Reverts paullouisageneau/libjuice#210
=> Revert "Shorten nomination timeout"

include/juice/juice.h, src/agent.c, src/agent.h, src/juice.c, test/server.c
Allows TURN servers to be added post agent creation
=> Add juice_add_turn_server API

src/agent.c, src/agent.h
Fixes https://github.com/paullouisageneau/libjuice/issues/261
=> Fix reuse of transaction ID in different STUN binding request

src/agent.c
=> Fix remote description already set check

src/agent.c
Fixes https://github.com/paullouisageneau/libjuice/issues/266
=> Unlock agent when resolving STUN and TURN server address resolution

src/crc32.c
Fixes https://github.com/paullouisageneau/libjuice/issues/302
=> Fix CRC32 table recalculation
