src/agent.c, test/main.c
For Windows, call WSAStartup in agent instead of expecting it to be called from outside.
=> Call WSAStartup on Windows

src/agent.c, src/socket.h, src/udp.c
This PR renames `ioctl()` and `close()` to prevent potential name collisions with defines.
=> Rename ioctl and close

include/juice/juice.h, src/agent.c, src/socket.h, src/udp.c, src/udp.h, test/connectivity.c
Implements https://github.com/paullouisageneau/libjuice/issues/12
Add support for UDP port range constraint in config via fields `local_port_range_begin` and `local_port_range_end` (values `0` mean disabled).
=> UDP port range in config

CMakeLists.txt, src/agent.c, src/agent.h, src/ice.c, test/connectivity.c, test/main.c, test/notrickle.c
- Prevent useless STUN probing before remote description
- Add non-trickled connectivity test
- Add logging on send error
=> Wait for remote description to unfreeze candidate pairs

src/agent.c, src/agent.h
This PR limits retransmissions for still pending pairs when selecting one.
Should fix https://github.com/paullouisageneau/libdatachannel/issues/155
=> More aggressive pair nomination

src/agent.c
This PR fixes the warning `Unable to unfreeze the pair: no matching entry` on peer reflexive candidates.
=> Fix pairs without entry

CMakeLists.txt, src/random.c, src/socket.h, src/thread.h
This drops support for Windows XP and Windows Vista.
Fixes https://github.com/paullouisageneau/libjuice/issues/44
=> Use BCryptGenRandom instead of CryptGenRandom on Windows

CMakeLists.txt, include/juice/juice.h, src/agent.c, src/ice.c, src/ice.h, src/juice.c, test/connectivity.c, test/notrickle.c
This PR introduces a new getter `juice_get_selected_candidates` to get the selected candidates pair.
It also enhances the completion logic and keeps local address translation only on macOS.
=> Add candidates pair getter

src/agent.c, src/agent.h
This PR introduces an idle state for STUN entries to prevent early checks.
=> Entry idle state

CMakeLists.txt
wsock32 is for the obsolete version of Windows Socket. libjuice is linked to ws2_32 (one for Windows Socket 2) and this is enough for calling Windows Socket APIs. More than that, the inclusion of wsock32 is incompatible with the Universal Windows App thing that Microsoft is pushing. To upload an app to their store, the app should comply to their sandbox environment thing, and inclusion of wsock32 is considered as a violation...
In case you want to know where I got this information from...
https://stackoverflow.com/questions/17797594/winsock2-h-vs-winsock2-h-and-wsock32-lib-vs-ws2-32-lib
=> Remove wsock32 for uwp compatibility.

src/random.c
`getrandom()` requires glibc 2.25+.
Fixes https://github.com/paullouisageneau/libjuice/issues/54
=> Check glibc version before using getrandom()

include/juice/juice.h, src/juice.c
This PR introduces proper negative error codes in API:
- `JUICE_ERR_INVALID`: Invalid argument
- `JUICE_ERR_FAILED`: Runtime error
- `JUICE_ERR_NOT_AVAIL`: Element not available
=> Properly define error codes in API

src/turn.c
I think there are two bugs in `find_ordered_transaction_id_rec`.
If the `id` is in the right half of the array then the stack will overflow since the pivot element will always be in the left half of the array.
Another problem is that the branch that searches in the left half of the array always starts at zero.
This will not result in an error but makes the binary search less efficient.
By the way: Thanks for making this great library. Its really nice that it has no dependencies and the code is really well written and understandable.
=> fix binary search for turn transaction id

src/agent.c, src/server.c, src/udp.c, src/udp.h
This PR fixes thread interruption when the host supports IPv6 but it has been disabled on loopback, for instance with `net.ipv6.conf.all.disable_ipv6 = 1`.
Fixes https://github.com/paullouisageneau/libjuice/issues/79
=> Fix thread interruption when loopback has no IPv6

src/agent.c
This PR changes STUN server keepalives to binding requests instead of indications, in accordance with [RFC 8445](https://tools.ietf.org/html/rfc8445).
=> Fix STUN server keepalives

src/udp.c
This PR changes `udp_sendto()` to map IPv4 to IPv6 for every non-Linux platform.
Should fix https://github.com/paullouisageneau/libdatachannel/issues/424
=> Fix *BSD support

CMakeLists.txt, include/juice/juice.h, src/agent.c, src/udp.c, test/bind.c, test/main.c
This PR adds a `bind_address` setting to the agent to bind only on one interface. This can be useful on a multihomed server.
=> Add bind address setting to agent

CMakeLists.txt, include/juice/juice.h
Right now on Linux all symbols, including those that are not part of the public API, are exported.
If juice is dynamically linked to a codebase that contains a symbol with the same name, juice
will use that one instead of its own version of that symbol. This can cause crashes or other types of instabilities.
This pull request causes symbols not marked with JUICE_EXPORT to be hidden to reduce
possible symbol collisions.
Hiding is accomplished with CMake C_VISIBILITY_PRESET option, which
automatically uses appropriate compiler option (-fvisibility on GCC).
This commit also replaces the JUICE_EXPORT macro by one automatically
generated by CMake, which should contain the appropriate definition for
the used compiler.
=> Hide not exported symbols by default

src/agent.c
This PR removes the clumsy usage of `sockerrno` when `agent_direct_send()` fails.
=> Clean up errno after agent_direct_send()

src/stun.c
This PR fixes missing realm and nonce attributes in CreatePermission or ChannelBind 438 Stale nonce error response sent by the server (server-side fix related to https://github.com/paullouisageneau/libjuice/pull/108 and https://github.com/paullouisageneau/libjuice/pull/109).
=> Fix missing attributes in server 438 error response

src/agent.c, src/agent.h, src/stun.c, src/stun.h
This PR implements the ALTERNATE-SERVER mechanism from [RFC 8489](https://datatracker.ietf.org/doc/html/rfc8489#section-10).
Implements https://github.com/paullouisageneau/libjuice/issues/88
=> Add TURN ALTERNATE-SERVER mechanism for agent

src/server.c
This PR fixes a segfault in server on TURN Allocate request with 0 lifetime caused by an attempt to log a NULL address, when log level is INFO.
Fixes https://github.com/paullouisageneau/violet/issues/9
=> Fix NULL address logging in server on TURN Allocate

include/juice/juice.h, src/juice.c, src/server.c, src/server.h, src/stun.c, src/stun.h
This PR refactors TURN credentials storage and adds the function `juice_server_add_credentials()` to dynamically add credentials.
=> Add dynamic TURN credentials

CMakeLists.txt
This PR applies multiple fixes to CMakeLists:
- Fix CMake exported target name from `LibJuice::juice` to `LibJuicel::LibJuice` to match the existing alias.
- Fix missing public include directory on install
- Make Threads a private dependency to export no dependency
=> CMake: Multiple fixes

src/agent.c
This PR fixes a possible attempt to send a STUN binding request after recovering from an ICE role conflict.
=> Fix possible binding without credentials error after ICE role conflict

src/agent.c
This PR silences the warning `Got STUN Binding error response, code=487`.
=> Silence warning on STUN error 487

CMakeLists.txt
This PR changes the CMake exported package name to `LibJuice` instead of `libjuice` and adds CMake config version.
=> Fix CMake exported package name

CMakeLists.txt, cmake/LibJuiceConfig.cmake
This PR introduces a CMake config file to add the former installed target name `LibJuice::juice` as an alias for retro-compatibility (The installed target name was fixed to be `LibJuice::LibJuice` in  https://github.com/paullouisageneau/libjuice/pull/124). It also changes the CMake config file destination to `lib` instead of `share`, as `share` should be reserved to platform-independent macros.
=>  CMake: Add retro-compatibility target alias and fix config file destination

src/agent.c, src/server.c, src/socket.h
This PR replaces `select()` by `poll()`, whose behavior is nowadays available on Microsoft Windows with `WSAPoll()`, to fix the limitation to 1024 file descriptors.
=> Replace select() by poll()

src/server.h
This PR reduces the default max allocations count in server to 1000 to fix https://github.com/paullouisageneau/libjuice/issues/127.
=> Reduce server default max allocations count

src/timestamp.c
`clock_gettime()` was incorrectly called with incorrect id `CLOCK_REALTIME`.
=> Fix timestamps to be monotonic

src/timestamp.c
This PR adds a workaround to support macOS < 10.12 which lacks `clock_gettime()`.
Fixes https://github.com/paullouisageneau/libjuice/issues/133
=> Workaround to support macOS < 10.12

src/agent.c, src/ice.c, src/ice.h
This PR makes candidate priority unique as required by [RFC 8445](https://datatracker.ietf.org/doc/html/rfc8445#section-5.1.2.1), as libjuice incorrectly computed the same priority for candidates with the same type and family.
=> Fix candidate priority computation

src/server.c
Looks like there is the memory leak in server cleanup. I've caught this on linux with valgrind and gcc's leak sanitizer.
Here is valgrind output:
```
$ valgrind --leak-check=full --track-origins=yes ./cmake-build-debug/tests 2> valgrind
...
$ cat valgrind
==20712== Memcheck, a memory error detector
==20712== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20712== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==20712== Command: ./cmake-build-debug/tests
==20712== 
==20712== 
==20712== HEAP SUMMARY:
==20712==     in use at exit: 34,176 bytes in 7 blocks
==20712==   total heap usage: 349 allocs, 342 frees, 891,343 bytes allocated
==20712== 
==20712== 34,176 (22,400 direct, 11,776 indirect) bytes in 1 blocks are definitely lost in loss record 4 of 4 …
```
=> Memory leak in server_do_destroy

CMakeLists.txt, include/juice/juice.h, src/agent.c, src/agent.h, src/conn.c, src/conn.h, src/conn_mux.c, src/conn_mux.h, src/conn_poll.c, src/conn_poll.h, src/conn_thread.c, src/conn_thread.h, src/server.c, src/turn.h, src/udp.c
This PR introduces an abstraction for ICE agent connections and implements 3 different concurrency mode:
- `POLL`: Each agent has its own UDP socket and agents share a single thread (default)
- `MUX`: Agents share a single UDP socket with multiplexing based on ICE ufrags
- `THREAD`: Each agent has its own UDP socket and thread (original behavior)
The mode can be changed per connection with `concurrency_mode` in config.
Implements https://github.com/paullouisageneau/libjuice/issues/144
=> Single-thread polling and UDP multiplexing support

src/agent.c
Fixes https://github.com/paullouisageneau/libjuice/issues/149
=> Keep TURN allocation alive before remote candidates are received

src/udp.c
This PR fixes `udp_set_diffserv()` by setting `IP_TOS` in addition to `IPV6_TCLASS` on the IPv6 socket to ensure the DSCP is also set on outgoing IPv4 traffic (`IPV6_V6ONLY` is disabled).
Fixes https://github.com/paullouisageneau/libdatachannel/issues/654
=> Fix DSCP not set on outgoing IPv4 traffic

Makefile
This PR is aimed to add the ability to compile for any i386 32-bit system when building directly with Make.
I see other deps libdatachannel libraries already have this feature via configure.
=> ability to compile for any 32-bit i386 system

src/agent.c
This PR filters out duplicate TURN servers in agent config as they will cause conflicts.
Fixes https://github.com/paullouisageneau/libjuice/issues/165
=> Ignore duplicate TURN servers in agent config

test/conflict.c, test/connectivity.c, test/gathering.c, test/mux.c, test/notrickle.c, test/thread.c, test/turn.c
This PR changes STUN and TURN servers in tests as people used my small test server in large-scale production. It also remove TURN servers where they were not necessary.
=> Change STUN and TURN servers in tests

src/agent.c
This PR fixes the automatic creation of peer reflexive candidates which possibly led to selecting of a pair featuring a peer reflexive candidates while another type would be expected. The candidate priorities should not be impacted.
=> Fix automatic creation of peer reflexive candidate

.clang-tidy, .github/workflows/build.yml, CMakeLists.txt
I got interested in this case #176. I've also run another linter (clang-tidy). Here is the output:
```
libjuice/src/conn_poll.c:341:3: warning: Potential leak of memory pointed to by 'conn_impl' [clang-analyzer-unix.Malloc]
JLOG_ERROR("UDP socket creation failed");
^
libjuice/src/log.h:33:25: note: expanded from macro 'JLOG_ERROR'
#define JLOG_ERROR(...) juice_log_write(JUICE_LOG_LEVEL_ERROR, __FILE__, __LINE__, __VA_ARGS__)
^
libjuice/src/conn_poll.c:333:27: note: Memory is allocated
conn_impl_t *conn_impl = calloc(1, sizeof(conn_impl_t));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libjuice/src/conn_poll.c:334:6: note: Assuming 'conn_impl' is non-null
if (!conn_impl) {
^~~~~~~~~~
libjuice/src/conn_poll.c:334:2: note: Taking false branch
if (!conn_impl) {
^
libjuice/src/conn_poll.c:340:6: note: …
```
=> Added option and initial config for clang-tidy

src/conn.c, src/conn_poll.c, src/stun.c
This PR fixes warnings after adding clang-tidy in https://github.com/paullouisageneau/libjuice/pull/177
=> Fix warnings from clang-tidy

src/agent.c
This PR disables limiting of retransmissions if the selected pair involves a relay. This should help when signaling is very slow, for instance when forwarding descriptions manually, otherwise the answerer may settle for the relay too early with filtered NATs.
Mitigation for https://github.com/paullouisageneau/libjuice/issues/180
=> Do not limit retransmissions if selected pair is relayed

src/server.c, test/server.c
This PR fixes issues with `juice_server_add_credentials()`: it ignored credentials with a non-zero (i.e. limited) lifetime and could cause memory corruption if no credentials were added on server creation.
Fixes https://github.com/paullouisageneau/libjuice/issues/184
=> Fix temporary server credentials issues

CMakeLists.txt, Makefile, include/juice/juice.h
This PR fixes the export define for Windows when not using the export header, as previously it would lead to incorrect behavior, for instance re-exported symbols when used as a static library in a dynamic library.
=> Fix export define for Windows

src/agent.c
Check pair on nomination request only if remote description is already present as requests can't be sent without ICE credentials anyway.
=> Fix scheduled check without remote on nomination request

README.md, src/agent.c, src/agent.h
This PR implements ICE PAC (Patiently Awaiting Connectivity) as specified in [RFC 8863](https://www.rfc-editor.org/rfc/rfc8863.html) and changes the STUN retransmission timings to align with the defaults from [RFC 8489](https://www.rfc-editor.org/rfc/rfc8489.html#section-6.2.1).
=> Implement ICE Patiently Awaiting Connectivity

src/ice.c
This PR fixes the parsing of end-of-candidates attribute which was ignored due to a typo.
=> Fix end-of-candidates attribute parsing in description

src/agent.c, src/server.c
This PR fixes allocation failure handling during configuration copy for both agent and server.
Fixes https://github.com/paullouisageneau/libjuice/issues/203
=> Fix allocation failure in config copy

src/agent.c, src/ice.c, src/ice.h
This PR fixes SDP parsing error logging so the library actually logs specific messages when ICE user fragment or password are missing instead of a generic message.
=> Fix SDP parsing error logging

README.md, src/agent.c, src/ice.c, src/ice.h
This PR adds support for the `ice-lite` attribute in remote description, as specified by [RFC 8839](https://www.rfc-editor.org/rfc/rfc8839.html).
=> Add support for ice-lite in remote description

src/agent.c
detection of Non-Symmetric Transport address doesn't release socket fds, which will cause high cpu load of polling for 0 ms.
=> Fix potential high cpu load of polling 0ms loop

src/agent.c
The nomination logic for the controlling agent is incorrect, resulting in nomination delays and busy spinning during nomination.
=> Fix nomination logic for controlling agent

CMakeLists.txt
On most Linux distributions (excluding the Debian family), 64-bit stuff goes into lib64, while 32-bit stuff goes into lib or lib32. The Debian family has their own special setup as well.
This change makes it so we install correctly regardless of FHS setup is used.
=> cmake: Use GNUInstallDirs to install files to the correct paths

src/agent.c
In src/socket.h SENETUNREACH is already defined as WSAENETUNREACH on Windows and ENETUNREACH on Linux.
While I'm unable to reproduce the build error locally (likely due to different mingw versions), I'm seeing github actions failing for the Godot WebRTC plugin [here](https://github.com/Faless/webrtc-native/actions/runs/6597706986/job/17924964327).
```
/home/runner/work/webrtc-native/webrtc-native/thirdparty/libdatachannel/deps/libjuice/src/agent.c:1601:14: error: 'ENETUNREACH' undeclared (first use in this function); did you mean 'SENETUNREACH'?
1601 |   if (ret == ENETUNREACH)
|              ^~~~~~~~~~~
|              SENETUNREACH
```
Looking at `src/socket.h` I can see that it was properly set up to handle the different WSA/Posix socket cases correctly already: …
=> Use SENETUNREACH to fix some windows builds

src/stun.c
=> Fix misalignment issue during STUN data reading

src/agent.c, src/log.c, src/thread.h
This PR removes the `ATOMIC_VAR_INIT` macro. It is useless in C11, deprecated in C17, and removed in C23.
=> Remove deprecated ATOMIC_VAR_INIT macro

src/udp.c
=> If socket allocations fails try again without IPv6

CMakeLists.txt, include/juice/juice.h, src/agent.c, src/juice.c, test/main.c, test/ufrag.c
In order to support Peer A and Peer B in WebRTC Direct, we need to be able to specify the ufrag and pwd of the localDescription. WebRTC Direct's documentation suggests replacing the ufrag and pwd with setLocalDescription. This is not compliant with the standard.
Therefore, I propose another solution, we can set ufrag and pwd in juice_create, which can satisfy both Peer A and Peer B's needs, and will not modify the existing logic in any way.
=> Add support for setting ICE ufrag and pwd

src/agent.c, src/agent.h, src/ice.c, src/ice.h, src/juice.c, test/ufrag.c
This PR introduces `agent_set_local_ice_attributes`() and `ice_is_valid_string()` to perform ICE attribute checks inside the agent.
=> Refactoring

include/juice/juice.h, src/agent.c, src/juice.c
This PR makes error codes more consistent for `juice_set_remote_description()` and `juice_add_remote_candidate()`.
=> Make error codes more consistent for remote description and candidates

src/conn_thread.c, test/notrickle.c
This PR fixes a deadlock when the user would call an API function from a callback in concurrency mode thread, typically `juice_get_local_description()` from `cb_gathering_done` for non-trickled ICE mode.
=> Fix deadlock on call from user callback in concurrency mode thread

src/agent.c
This PR prevents the USE-CANDIDATE attribute from being set after nomination when controlling. In particular, it removes the attribute from STUN binding requests sent as keepalives.
=> Do not set USE-CANDIDATE after nomination when controlling

src/conn_mux.c, src/conn_poll.c, src/conn_thread.c, src/server.c
Should fix https://github.com/paullouisageneau/libjuice/issues/269
=> Prevent passing NULL buffer to sendto() for better compatibility with C standard libraries

CMakeLists.txt
Setting `BUILD_SHARED_LIBS` to `OFF` now builds the `LibJuice::LibJuice` target statically.
=> CMake: Comply with BUILD_SHARED_LIBS option

src/conn.c
In #274, I added release_registry in conn_create, but forgot to lock entry->mutex.
Let's fix this by holding the mutex longer.
Note that it is not possible to release the mutex once and re-lock it just before release_registry. This is because of the possibility of deadlock.
Also fixed a bug where registry->mutex is referenced even though the registry is NULL.
=> Fixed race condition potentially resulting in referencing freed registry

src/server.c, src/turn.c
TURN permissions were applied by the server when sending but not when relaying.
=> Fix TURN server permissions enforcement when relaying

include/juice/juice.h, src/conn.c, src/conn.h, src/conn_mux.c, src/conn_mux.h
In order to implement WebRTC Direct PeerB, we need to capture STUN requests from unknown clients and return the client's information. Once PeerB receives this information, it will construct the client's SDP and establish a connection with the client on its own.
=> Add callback to get unhandled STUN binding requests from mux

src/picohash.h
Otherwise any connection attempt with a ufrag longer than 64 characters causes the process to exit with a SIGBUS error.
I have not been able to isolate this into a test, but at runtime it crashes the remote process every single time.
=> fix: set hash_reset before invoking it

src/agent.c
The peer reflexive candidate is not added when receiving a request over the relay, which can cause relaying to fail when the remote peer has no TURN server and is behind an endpoint-dependent NAT.
Should fix https://github.com/paullouisageneau/libjuice/issues/285
=> Fix peer reflexive candidate for TURN-relayed request

src/agent.c
This PR prevents failure when the binding response has non symmetric address after the initial check. It also ensures `selected_entry` stays consistent even if the nominated pair changes state.
This should mitigate issue https://github.com/paullouisageneau/libjuice/issues/304 with macOS.
=> Prevent connectivity lost on non symmetric address

src/agent.c, src/conn.c, src/conn.h, src/conn_poll.c, src/conn_poll.h, src/ice.h, src/udp.c, test/main.c, test/tcp.c
Don't kill the entire connection because TCP has errored
=> Fix TCP error handling in conn_poll
